//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTransactionApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTransaction
    {
        public int SalesTransactionId { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public double Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
